export const GET_ALL_FBI = "GET_ALL_FBI";
export const GET_REWARD_FBI = "GET_REWARD_FBI";
export const GET_CORRECT_ANSWER = "GET_CORRECT_ANSWER";

export const GET_INCORRECT1_ANSWER = "GET_INCORRECT1_ANSWER";
export const GET_INCORRECT2_ANSWER = "GET_INCORRECT2_ANSWER";
export const LOAD_LEVEL1 = "LOAD_LEVEL1";
export const LOAD_LEVEL2 = "LOAD_LEVEL2";
export const LOAD_LEVEL3 = "LOAD_LEVEL3";
export const POST_CRIMINAL = "POST_CRIMINAL";
export const DETAIL_CRIMINAL = "DETAIL_CRIMINAL";
export const CLEAR_STATE = "CLEAR_STATE";
