export const GET_ALL_FBI = "GET_ALL_FBI";
export const GET_REWARD_FBI = "GET_REWARD_FBI";
export const GET_CORRECT_ANSWER = "GET_CORRECT_ANSWER";

export const GET_INCORRECT1_ANSWER = "GET_INCORRECT1_ANSWER";
export const GET_INCORRECT2_ANSWER = "GET_INCORRECT2_ANSWER";
